services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_db:/app/db_data
    environment:
      - DJANGO_DB_PATH=/app/db_data/db.sqlite3

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  backend_db:
