"""
Прозрачный анализ тональности криптовалютных новостей
на основе словаря сигнальных слов.

Без внешних AI-API.

Результат находится в диапазоне [-1, 1]:

    -1.0 — максимально негативный сигнал
     0.0 — нейтральный / нет сигналов
     1.0 — максимально позитивный сигнал
"""

import re


POSITIVE_WORDS = [
    # Цена / движение рынка
    "surge",
    "surges",
    "surged",
    "rally",
    "rallies",
    "rallied",
    "soar",
    "soars",
    "soared",
    "bullish",
    "bull run",
    "bull market",
    "gain",
    "gains",
    "gained",
    "jump",
    "jumps",
    "jumped",
    "rise",
    "rises",
    "rising",
    "rose",
    "rebound",
    "rebounded",
    "recovery",
    "recover",
    "recovered",
    "breakout",
    "breakthrough",
    "uptrend",
    "upside",
    "higher",
    "new high",
    "record high",
    "all-time high",
    "all time high",
    "ath",
    "new ath",
    "price target raised",
    "target raised",

    # Позитивные оценки
    "positive",
    "optimistic",
    "optimism",
    "optimist",
    "confidence",
    "confident",
    "strong",
    "strength",
    "outperform",
    "outperformed",
    "outperformance",
    "undervalued",
    "promising",
    "favorable",
    "favourable",
    "healthy",
    "resilient",
    "resilience",
    "momentum",
    "strong momentum",

    # Покупки / спрос
    "buy",
    "buys",
    "buying",
    "bought",
    "accumulate",
    "accumulation",
    "accumulating",
    "demand",
    "strong demand",
    "buying pressure",
    "institutional buying",
    "institutional demand",
    "whale accumulation",
    "whales accumulating",
    "increased demand",
    "capital inflow",

    # ETF / инвестиции
    "etf approval",
    "etf approved",
    "etf inflows",
    "etf inflow",
    "spot etf",
    "spot bitcoin etf",
    "spot ethereum etf",
    "fund inflows",
    "fund inflow",
    "institutional inflows",
    "institutional investment",
    "institutional adoption",
    "institutional buying",
    "investment inflows",
    "net inflows",
    "record inflows",

    # Adoption / использование
    "adoption",
    "adopt",
    "adopted",
    "mainstream adoption",
    "mass adoption",
    "institutional adoption",
    "user growth",
    "user adoption",
    "network growth",
    "ecosystem growth",
    "developer growth",
    "developer adoption",
    "increased usage",
    "growing usage",
    "transaction growth",
    "transaction volume",
    "record transactions",
    "record activity",

    # Разработка / технология
    "upgrade",
    "upgraded",
    "upgrade approved",
    "successful upgrade",
    "successful launch",
    "launch",
    "launched",
    "release",
    "released",
    "milestone",
    "milestone reached",
    "breakthrough",
    "innovation",
    "innovative",
    "scaling",
    "scalability",
    "improved scalability",
    "performance improvement",
    "network upgrade",
    "protocol upgrade",
    "hard fork",
    "successful hard fork",

    # Партнёрства
    "partnership",
    "partnerships",
    "partnered",
    "strategic partnership",
    "major partnership",
    "integration",
    "integrated",
    "collaboration",
    "strategic collaboration",
    "deal",
    "agreement",
    "strategic agreement",
    "adoption partnership",

    # DeFi
    "defi growth",
    "defi adoption",
    "tvl growth",
    "tvl increase",
    "total value locked",
    "liquidity growth",
    "liquidity increase",
    "yield growth",
    "staking growth",
    "staking adoption",
    "staking increase",
    "validator growth",

    # Сеть / технические показатели
    "hashrate growth",
    "record hashrate",
    "network hashrate",
    "network activity",
    "increased activity",
    "record network activity",
    "low fees",
    "fee reduction",
    "faster transactions",
    "network stability",
    "stable network",
    "high network security",

    # Новости / регуляторы
    "approval",
    "approved",
    "regulatory approval",
    "regulatory clarity",
    "clear regulation",
    "favorable regulation",
    "favourable regulation",
    "regulatory progress",
    "legal clarity",
    "legal victory",
    "court victory",
    "lawsuit dismissed",
    "case dismissed",
    "charges dropped",
    "ban lifted",
    "restriction lifted",
    "regulatory breakthrough",

    # Проекты / бизнес
    "growth",
    "growing",
    "expansion",
    "expanded",
    "revenue growth",
    "profit growth",
    "record revenue",
    "record profits",
    "increased revenue",
    "increased profits",
    "funding",
    "funded",
    "investment",
    "invested",
    "fundraising",
    "successful fundraising",
    "valuation increase",

    # Позитивные рыночные сигналы
    "short squeeze",
    "squeeze",
    "liquidated shorts",
    "short liquidations",
    "short covering",
    "decreasing selling pressure",
    "reduced selling pressure",
    "seller exhaustion",
    "supply shock",
    "supply reduction",
    "reduced supply",
    "scarcity",
    "deflationary",
    "burn",
    "token burn",
    "tokens burned",
    "reduced supply",
    "exchange outflow",
    "exchange outflows",
]


NEGATIVE_WORDS = [
    # Падение цены
    "crash",
    "crashes",
    "crashed",
    "plunge",
    "plunges",
    "plunged",
    "plummet",
    "plummets",
    "plummeted",
    "drop",
    "drops",
    "dropped",
    "fall",
    "falls",
    "falling",
    "fell",
    "decline",
    "declines",
    "declined",
    "downturn",
    "downtrend",
    "downside",
    "selloff",
    "sell-off",
    "selling",
    "sell pressure",
    "selling pressure",
    "bearish",
    "bear market",
    "bear run",
    "lower",
    "new low",
    "record low",
    "price target cut",
    "target lowered",

    # Негативные оценки
    "negative",
    "pessimistic",
    "pessimism",
    "fear",
    "fearful",
    "panic",
    "uncertainty",
    "uncertain",
    "concern",
    "concerns",
    "worried",
    "worry",
    "risk",
    "risky",
    "weak",
    "weakness",
    "underperform",
    "underperformed",
    "undervalue",
    "overvalued",

    # Потери
    "loss",
    "losses",
    "lost",
    "losing",
    "damage",
    "damages",
    "declining revenue",
    "revenue decline",
    "profit decline",
    "financial losses",

    # Продажи / оттоки
    "sell",
    "sells",
    "sold",
    "selling",
    "sell pressure",
    "selling pressure",
    "whale selling",
    "whales selling",
    "whale distribution",
    "distribution",
    "outflow",
    "outflows",
    "capital outflow",
    "fund outflows",
    "fund outflow",
    "institutional selling",
    "net outflows",
    "exchange inflow",
    "exchange inflows",

    # Ликвидации
    "liquidation",
    "liquidations",
    "liquidated",
    "mass liquidation",
    "mass liquidations",
    "forced liquidation",
    "forced selling",
    "long liquidation",
    "long liquidations",
    "liquidation cascade",
    "liquidation event",
    "leveraged liquidation",
    "margin call",
    "margin calls",

    # Хакеры / безопасность
    "hack",
    "hacks",
    "hacked",
    "hacker",
    "hackers",
    "exploit",
    "exploited",
    "exploiter",
    "security breach",
    "security vulnerability",
    "vulnerability",
    "vulnerabilities",
    "attack",
    "attacked",
    "51% attack",
    "51 percent attack",
    "bridge hack",
    "smart contract exploit",
    "protocol exploit",
    "wallet hack",
    "exchange hack",
    "data breach",
    "private key leak",
    "private keys leaked",

    # Мошенничество
    "fraud",
    "fraudulent",
    "scam",
    "scams",
    "scam token",
    "rug pull",
    "rugpull",
    "ponzi",
    "ponzi scheme",
    "pyramid scheme",
    "fake",
    "fake token",
    "phishing",
    "money laundering",
    "laundering",
    "stolen funds",
    "stolen crypto",
    "stolen tokens",

    # Регуляторы / закон
    "ban",
    "banned",
    "ban crypto",
    "crypto ban",
    "crackdown",
    "regulatory crackdown",
    "regulation crackdown",
    "regulatory pressure",
    "regulatory risk",
    "regulatory uncertainty",
    "legal action",
    "lawsuit",
    "lawsuits",
    "sued",
    "investigation",
    "investigated",
    "subpoena",
    "indictment",
    "indicted",
    "charges",
    "criminal charges",
    "fine",
    "fined",
    "penalty",
    "penalties",
    "sanctions",
    "sanctioned",
    "enforcement action",
    "sec lawsuit",
    "sec investigation",
    "regulatory violation",
    "violation",

    # Биржи / проекты
    "bankrupt",
    "bankruptcy",
    "insolvent",
    "insolvency",
    "default",
    "defaulted",
    "collapse",
    "collapsed",
    "shutdown",
    "shut down",
    "closed",
    "closure",
    "delist",
    "delisted",
    "delisting",
    "suspended",
    "suspension",
    "withdrawal freeze",
    "withdrawals halted",
    "trading halted",
    "trading suspended",

    # Стейблкоины
    "depeg",
    "depegged",
    "depegging",
    "stablecoin depeg",
    "lost peg",
    "peg lost",
    "below peg",
    "liquidity crisis",

    # Сеть
    "network outage",
    "outage",
    "network failure",
    "network congestion",
    "congestion",
    "downtime",
    "chain halt",
    "blockchain halt",
    "transaction failure",
    "failed transactions",
    "high fees",
    "fee spike",
    "network instability",
    "network attack",

    # DeFi
    "defi hack",
    "defi exploit",
    "protocol failure",
    "liquidity crisis",
    "liquidity drain",
    "liquidity shortage",
    "tvl decline",
    "tvl decrease",
    "tvl collapse",
    "staking decline",

    # Токены
    "token unlock",
    "token unlocks",
    "large token unlock",
    "mass token unlock",
    "token dilution",
    "dilution",
    "inflation",
    "inflationary",
    "supply increase",
    "increased supply",
    "token dump",
    "dump",
    "dumping",
    "whale dump",

    # Майнинг
    "mining decline",
    "miner selling",
    "miner capitulation",
    "mining difficulty",
    "hashrate decline",
    "hashrate drop",
    "mining shutdown",

    # Общие негативные сигналы
    "warning",
    "warns",
    "warning signs",
    "red flag",
    "red flags",
    "threat",
    "threatens",
    "danger",
    "dangerous",
    "critical",
    "crisis",
    "market crisis",
    "liquidity crisis",
    "contagion",
    "market contagion",
]


def _count_signals(text: str, words: list[str]) -> int:
    """Подсчитывает количество вхождений сигнальных слов и фраз."""

    count = 0

    for word in words:
        pattern = rf"\b{re.escape(word)}\b"
        count += len(re.findall(pattern, text))

    return count


def score_text(text: str) -> float:
    """
    Рассчитывает тональность новости.

    Формула:

        (positive - negative) / (positive + negative)

    Результат:

        -1.0 — негативный
         0.0 — нейтральный
         1.0 — позитивный
    """

    if not text:
        return 0.0

    lower = text.lower()

    positive_count = _count_signals(lower, POSITIVE_WORDS)
    negative_count = _count_signals(lower, NEGATIVE_WORDS)

    total = positive_count + negative_count

    if total == 0:
        return 0.0

    return (positive_count - negative_count) / total