# Generated by Django 5.0.6 on 2026-08-21 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('coingecko_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('PRICE_API', 'Price API'), ('NEWS_RSS', 'News RSS')], max_length=20)),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('MOMENTUM_24H', 'Ценовой моментум за 24ч, %'), ('MOMENTUM_7D', 'Ценовой моментум за 7д, %'), ('VOLUME_CHANGE_24H', 'Изменение объёма торгов за 24ч, %'), ('VOLATILITY_7D', 'Волатильность за 7д (std дневных доходностей)'), ('NEWS_SENTIMENT_AVG', 'Средняя тональность новостей (48ч, взвеш. по свежести)'), ('NEWS_VOLUME_48H', 'Количество новостей за 48ч')], max_length=30)),
                ('value', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('window_label', models.CharField(blank=True, max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='predictor.asset')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_hours', models.IntegerField(default=24)),
                ('direction', models.CharField(choices=[('UP', 'Рост'), ('DOWN', 'Падение'), ('FLAT', 'Без изменений')], max_length=10)),
                ('probability_up', models.FloatField()),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Средний'), ('HIGH', 'Высокий')], max_length=10)),
                ('risk_reasons', models.TextField()),
                ('arguments', models.TextField()),
                ('score_breakdown', models.JSONField(default=dict)),
                ('price_at_prediction', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает проверки'), ('EVALUATED', 'Проверен')], default='PENDING', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='predictor.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('price_at_evaluation', models.FloatField()),
                ('actual_pct_change', models.FloatField()),
                ('actual_direction', models.CharField(choices=[('UP', 'Рост'), ('DOWN', 'Падение'), ('FLAT', 'Без изменений')], max_length=10)),
                ('was_correct', models.BooleanField()),
                ('probability_error', models.FloatField()),
                ('prediction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='predictor.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='RawPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('price_usd', models.FloatField()),
                ('volume_24h_usd', models.FloatField(blank=True, null=True)),
                ('market_cap_usd', models.FloatField(blank=True, null=True)),
                ('pct_change_24h', models.FloatField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='predictor.asset')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='predictor.source')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('mentioned_assets', models.ManyToManyField(blank=True, related_name='articles', to='predictor.asset')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='predictor.source')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Успех'), ('PARTIAL', 'Частично'), ('FAILED', 'Ошибка')], max_length=10)),
                ('records_fetched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='predictor.source')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
